services:
  postgres:
    image: postgres:12.22
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres-leonardo:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=leonardo
      - POSTGRES_USER=leonardo
      - POSTGRES_DB=leonardo
